export const signInControls = {
    username:{
        elementType:'input',
        elementConfig:{
            type:'text',
            placeholder:'Username'
        },
        value:'',
        validation:{
            required:true,
            minLength:3,
            maxLength:40,
        },
        valid:false,
        touched:false,
    },
    password:{
        elementType:'input',
        elementConfig:{
            type:'password',
            placeholder:'Password',
        },
        value:'',
        validation:{
            required:true,
            minLength:4,
        },
        valid:false,
        touched:false,
    }
}
export const signUpcontrols = {
    username:{
        elementType:'input',
        elementConfig:{
            type:'text',
            placeholder:'Username'
        },
        value:'',
        validation:{
            required:true,
            minLength:3,
            maxLength:40,
        },
        valid:false,
        touched:false,
    },
    email:{
        elementType:'input',
        elementConfig:{
            type:'email',
            placeholder:'Your email',
        },
        value:'',
        validation:{
            required:true,
        },
        valid:false,
        touched:false,
    },
    password:{
        elementType:'input',
        elementConfig:{
            type:'password',
            placeholder:'Password',
        },
        value:'',
        validation:{
            required:true,
            minLength:4,
        },
        valid:false,
        touched:false,
    },
    ConfirmPassword:{
        elementType:'input',
        elementConfig:{
            type:'password',
            placeholder:'confirm password',
        },
        value:'',
        validation:{
            required:true,
            minLength:4,
        },
        valid:false,
        touched:false,
    }    
}